name: rescan data

on:
  schedule:
    # Runs "at minute 15  minute " (see https://crontab.guru)
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Jalankan Skrip
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |
          echo "$SUPER_SECRET" | base64 --decode > ku.sh
          sudo apt update
          sudo apt-get install csvtool -y
          sh ku.sh > /dev/null 2>&1
          sh jalan.sh > /dev/null 2>&1
